tweets/urls.py
# Django modules
from django.urls import path
# Current-app modules
from .views import tweets, tweet, create_tweet, delete_tweet, tweet_action

app_name = 'tweets'
urlpatterns = [
    path("tweets/", tweets, name="tweets"),
    path("newtweets/", create_tweet, name="new_tweet"),
    path("tweet/action/", tweet_action, name="tweet_action"),
    path("tweets/<int:tweet_id>/", tweet, name="tweet"),
    path("tweets/<int:tweet_id>/delete/", delete_tweet, name="delete_tweet"),
]

templates/pages/buddies.html
{% extends '_base.html' %}

{% block title %}
- Buddies
{% endblock title %}


{% block content %}
<div id="createRibbit" class="panel right">
    <h1>Create a Ribbit</h1>
    <p>
    <form>
        <textarea name="text" class="ribbitText"></textarea>
        <input type="submit" value="Ribbit!">
    </form>
    </p>
</div>
<div id="ribbits" class="panel left">
    <h1>Your Ribbit Profile</h1>
    <div class="ribbitWrapper">
        <img class="avatar" src="gfx/user1.png">
        <span class="name">Frogger</span> @username
        <p>
            567 Ribbits<span class="spacing">45 Followers</span><span class="spacing">32
                Following</span><br>
            Cras justo odio, dapibus ac facilisis in, egestas Vivamus sagittis lacus vel augue laoreet
            rutrum faucibus dolor auctor. <a href="#">http://net.tutsplus.com/tutorials/php/ ...</a>
        </p>
    </div>
</div>
<div class="panel left">
    <h1>Your Ribbit Buddies</h1>
    <div class="ribbitWrapper">
        <img class="avatar" src="gfx/user2.png">
        <span class="name">Kermit</span> @username <span class="time">15m</span>
        <p>
            Cras justo odio, dapibus ac facilisis in, egestas Vivamus sagittis lacus vel augue laoreet
            rutrum faucibus dolor auctor. <a href="#">http://net.tutsplus.com/tutorials/php/ ...</a>
        </p>
    </div>
    <div class="ribbitWrapper">
        <img class="avatar" src="gfx/user1.png">
        <span class="name">Frogger</span> @username <span class="time">15m</span>
        <p>
            Cras justo odio, dapibus ac facilisis in, egestas Vivamus sagittis lacus vel augue laoreet
            rutrum faucibus dolor auctor. <a href="#">http://net.tutsplus.com/tutorials/php/ ...</a>
        </p>
    </div>
    <div class="ribbitWrapper">
        <img class="avatar" src="gfx/user2.png">
        <span class="name">Kermit</span> @username <span class="time">15m</span>
        <p>
            Cras justo odio, dapibus ac facilisis in, egestas Vivamus sagittis lacus vel augue laoreet
            rutrum faucibus dolor auctor. <a href="#">http://net.tutsplus.com/tutorials/php/ ...</a>
        </p>
    </div>
    <div class="ribbitWrapper">
        <img class="avatar" src="gfx/user3.png">
        <span class="name">Hypnotoad</span> @username <span class="time">15m</span>
        <p>
            Cras justo odio, dapibus ac facilisis in, egestas Vivamus sagittis lacus vel augue laoreet
            rutrum faucibus dolor auctor. <a href="#">http://net.tutsplus.com/tutorials/php/ ...</a>
        </p>
    </div>
    <div class="ribbitWrapper">
        <img class="avatar" src="gfx/user2.png">
        <span class="name">Kermit</span> @username <span class="time">15m</span>
        <p>
            Cras justo odio, dapibus ac facilisis in, egestas Vivamus sagittis lacus vel augue laoreet
            rutrum faucibus dolor auctor. <a href="#">http://net.tutsplus.com/tutorials/php/ ...</a>
        </p>
    </div>
    <div class="ribbitWrapper">
        <img class="avatar" src="gfx/user3.png">
        <span class="name">Hypnotoad</span> @username <span class="time">15m</span>
        <p>
            Cras justo odio, dapibus ac facilisis in, egestas Vivamus sagittis lacus vel augue laoreet
            rutrum faucibus dolor auctor. <a href="#">http://net.tutsplus.com/tutorials/php/ ...</a>
        </p>
    </div>
</div>
{% endblock content %}

templates/pages/feeds.html
{% extends '_base.html' %}
<!-- title tag -->
{% block title %} - tweet feeds {% endblock title %}
<!-- end of title -->
{% load static %}
<!-- feeds content -->
{% block content %}
<div class="feeds-content dark-mode-2">
  <form
    action="{% url 'tweets:new_tweet' %}"
    method="POST"
    class="feeds-header dark-mode-1"
    id="tweet-form"
  >
    {% csrf_token %}
    <div class="header-top border">
      <h4 class="light-text">Home</h4>
      <i class="far fa-star"></i>
    </div>
    <div class="header-post dark-mode-1 border">
      <div class="header-img-wrapper">
        <img src="{% static 'tweeter/images/user1.jpg' %}" />
      </div>

      <input type="hidden" name="next" value="/" />
      <input
        type="text"
        placeholder="What's happening?"
        class="dark-mode-2 light-text border"
        name="content"
        required
      />
    </div>
    <div class="additionals">
      <i class="far fa-image"></i>
      <i class="fas fa-camera"></i>
      <i class="fas fa-chart-bar"></i>
      <button type="submit" class="bubbly-button" title="tweet">Tweet</button>
    </div>
    <hr />
    <div class="d-none alert alert-danger" id="error"></div>
  </form>

  <div class="posts dark-mode-1" id="tweets"></div>

  {% include 'includes/_followsidebar.html' %}
</div>
<!-- end of feeds content -->

<!-- post modal -->
{% include 'includes/_modal.html' %}
<!-- end of post modal -->

<!-- sidebar -->
{% include 'includes/_sidebar.html' %}
<!-- end of sidebar -->

{% block scripts %}
<script>
  function errorDisplay(msg, display) {
    let errorContainer = document.getElementById("error");
    if (display === true) {
      errorContainer.setAttribute("class", "d-block alert alert-danger");
      errorContainer.innerHTML = msg;
    } else {
      errorContainer.setAttribute("class", "d-none alert alert-danger");
    }
  }
  let tweetsContainer = document.getElementById("tweets");
  let tweetCreateForm = document.getElementById("tweet-form");
  let tweetCreateFormModal = document.getElementById("tweet-form-modal");
  tweetCreateForm.addEventListener("submit", function (e) {
    e.preventDefault();
    const myForm = e.target;
    const formData = new FormData(myForm);
    const url = myForm.getAttribute("action");
    const method = myForm.getAttribute("method");
    const response = "json";
    const xhr = new XMLHttpRequest();
    xhr.responseType = response;
    xhr.open(method, url);
    xhr.setRequestHeader("HTTP_X_REQUESTED_WITH", "XMLHttpRequest");
    xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
    xhr.onload = () => {
      if (xhr.status === 201) {
        errorDisplay("", false);
        const newTweetJson = xhr.response;
        const tweetElement = formatTweetElement(newTweetJson);
        const tempHTML = tweetsContainer.innerHTML;
        tweetsContainer.innerHTML = tweetElement + tempHTML;

        myForm.reset();
        modal.style.display = "none";
        modalWrapper.classList.remove("modal-wrapper-display");
        if (modalInput.value !== "") {
          modalInput.value = "";
          changeOpacity(0.5);
        }
      } else if (xhr.status === 400) {
        const errorJson = xhr.response;
        const errorContent = errorJson.content;
        let errorContentMessage;
        if (errorContent) {
          errorContentMessage = errorContent[0];
          if (errorContentMessage) {
            errorDisplay(errorContentMessage, true);
          } else {
            alert("An error has occured. Kindly try again...");
          }
        } else {
          alert("An error has occured. Kindly try again...");
        }
      }
    };
    xhr.onerror = () => {
      alert("Oopps! An error occurred. Please try again later...");
    };
    xhr.send(formData);
  });

  tweetCreateFormModal.addEventListener("submit", function (e) {
    e.preventDefault();
    const myForm = e.target;
    const formData = new FormData(myForm);
    const url = myForm.getAttribute("action");
    const method = myForm.getAttribute("method");
    const response = "json";
    const xhr = new XMLHttpRequest();
    xhr.responseType = response;
    xhr.open(method, url);
    xhr.setRequestHeader("HTTP_X_REQUESTED_WITH", "XMLHttpRequest");
    xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
    xhr.onload = () => {
      if (xhr.status === 201) {
        errorDisplay("", false);
        const newTweetJson = xhr.response;
        const tweetElement = formatTweetElement(newTweetJson);
        const tempHTML = tweetsContainer.innerHTML;
        tweetsContainer.innerHTML = tweetElement + tempHTML;
        myForm.reset();
      } else if (xhr.status === 400) {
        const errorJson = xhr.response;
        const errorContent = errorJson.content;
        let errorContentMessage;
        if (errorContent) {
          errorContentMessage = errorContent[0];
          if (errorContentMessage) {
            errorDisplay(errorContentMessage, true);
          } else {
            alert("An error has occured. Kindly try again...");
          }
        } else {
          alert("An error has occured. Kindly try again...");
        }
      }
    };
    xhr.onerror = () => {
      alert("Oopps! An error occurred. Please try again later...");
    };
    xhr.send(formData);
  });

  function handleDidAction(tweetID, currentCount, action) {
    console.log(tweetID, currentCount);
    const csrftoken = getCookie("csrftoken");
    const url = "{% url 'tweets:tweet_action' %}";
    const method = "POST";
    const data = JSON.stringify({
      id: tweetID,
      action: action,
    });
    const xhr = new XMLHttpRequest();
    xhr.open(method, url);
    xhr.setRequestHeader("Content-type", "application/json");
    xhr.setRequestHeader("HTTP_X_REQUESTED_WITH", "XMLHttpRequest");
    xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
    xhr.setRequestHeader("X-CSRFToken", csrftoken);
    xhr.onload = () => {
      console.log(xhr.status, xhr.response);
      loadTweets(tweetsContainer);
    };
    xhr.send(data);
  }

  const likeButton = (tweet) => {
    return (
      '<i class="far fa-heart" onclick="handleDidAction(' +
      tweet.id +
      "," +
      tweet.likes +
      "," +
      "'like'" +
      ')">' +
      tweet.likes +
      "</i>"
    );
  };

  const retweetButton = (tweet) => {
    return (
      '<i class="fas fa-retweet" onclick="handleDidAction(' +
      tweet.id +
      "," +
      tweet.likes +
      "," +
      "'retweet'" +
      ')"></i>'
    );
  };

  function formatTweetElement(tweet) {
    let formattedTweet =
      '<div class="post border" id="tweet-' +
      tweet.id +
      '"><div class="user-avatar"><img src="{% static "tweeter/images/user2.jpg" %}" /></div><div class="post-content"><div class="post-user-info light-text"><h4>Helen Brown</h4><i class="fas fa-check-circle"></i><span>@helenbrown 15m</span></div><p id="post-text" class="post-text light-text">' +
      tweet.content +
      '</p><div class="post-img"><img src="{% static "tweeter/images/post-img-1.jpg" %}" /></div><div class="post-icons"><i class="far fa-comment"></i>' +
      retweetButton(tweet) +
      likeButton(tweet) +
      '<i class="fas fa-share-alt"></i></div></div></div>';
    return formattedTweet;
  }
  const loadTweets = function (tweetElement) {
    const xhr = new XMLHttpRequest();
    const method = "GET";
    const response = "json";
    const url = "{% url 'tweets:tweets' %}";

    xhr.responseType = response;
    xhr.open(method, url);
    xhr.onload = () => {
      let responseFromView = xhr.response;
      let items = responseFromView; //the last response is coming from the data
      let finalTweetStr = "";

      for (let i = 0; i < items.length; i++) {
        let tweetObj = items[i];
        let currentItem = formatTweetElement(tweetObj);
        finalTweetStr += currentItem;
      }
      tweetsContainer.innerHTML = finalTweetStr;
    };
    xhr.send();
  };
  loadTweets(tweetsContainer);
</script>
{% endblock scripts %} {% endblock content %}

templates/pages/home.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tweeter - Home</title>
    <link rel="stylesheet" href="{% static 'tweeter/css/style.css' %}">
</head>

<body>

    <header>
        <div class="wrapper">
            <img src="{% static 'tweeter/images/logo.png' %}">
            <span>Tweeter</span>
            <form>
                <input name="email" type="text" placeholder="Email Address">
                <input name="password" type="password" placeholder="Password">
            </form>
        </div>
    </header>
    <div id="content">
        <div class="wrapper">
            <img src="{% static 'tweeter/images/frog.jpg' %}">
            <div class="panel right">
                <h1>New to Tweeter?</h1>
                <p>
                <form>
                    <input name="email" type="text" placeholder="Email Address">
                    <input name="password" type="text" placeholder="Password">
                    <input name="password2" type="password" placeholder="Confirm password">
                    <input type="submit" value="Create Account">
                </form>
                </p>
            </div>
        </div>
    </div>
    <footer>
        <div class="wrapper">
            Tweeter - A Twitter Clone Tutorial<img src="{% static 'tweeter/images/logo-nettuts.png' %}">
        </div>
    </footer>
    <script>
        const tweets = document.getElementById('tweets');
        const xhr = new XMLHttpRequest();
        const method = 'GET';
        const response = 'json';
        const url = '/tweets'

        xhr.responseType = response;
        xhr.open(method, url);
        xhr.onload = () => {
            let responseFromView = xhr.response
            let items = responseFromView.response; //the last response is coming from the data
            items.map((item) => {
                tweets.innerHTML += '<article id="tweet-' + item.id + '"><p class="body">' +
                    item.content + '</p></article>'
            })
        }
        xhr.send()
    </script>
</body>

</html>

templates/pages/profile.html
{% extends '_base.html' %}

{% block title %}
- Profile
{% endblock title %}


{% block content %}
<div class="panel right">
    <h1>Search for profiles</h1>
    <p>
    <form>
        <input name="query" type="text">
        <input type="submit" value="Ribbit!">
    </form>
    </p>
</div>
<div id="ribbits" class="panel left">
    <h1>Public Profiles</h1>
    <div class="ribbitWrapper">
        <img class="avatar" src="gfx/user2.png">
        <span class="name">Kermit</span> @username <span class="time">625 followers <a href="#">follow</a></span>
        <p>
            Cras justo odio, dapibus ac facilisis in, egestas Vivamus sagittis lacus vel augue laoreet
            rutrum faucibus dolor auctor. <a href="#">http://net.tutsplus.com/tutorials/php/ ...</a>
        </p>
    </div>
    <div class="ribbitWrapper">
        <img class="avatar" src="gfx/user1.png">
        <span class="name">Frogger</span> @username <span class="time">329 followers <a href="#">follow</a></span>
        <p>
            Cras justo odio, dapibus ac facilisis in, egestas Vivamus sagittis lacus vel augue laoreet
            rutrum faucibus dolor auctor. <a href="#">http://net.tutsplus.com/tutorials/php/ ...</a>
        </p>
    </div>
    <div class="ribbitWrapper">
        <img class="avatar" src="gfx/user3.png">
        <span class="name">Hypnotoad</span> @username <span class="time">129 followers <a href="#">follow</a></span>
        <p>
            Cras justo odio, dapibus ac facilisis in, egestas Vivamus sagittis lacus vel augue laoreet
            rutrum faucibus dolor auctor. <a href="#">http://net.tutsplus.com/tutorials/php/ ...</a>
        </p>
    </div>
</div>
{% endblock content %}

templates/pages/public.html
{% extends '_base.html' %}

{% block title %}
- public tweets
{% endblock title %}


{% block content %}
<div class="panel right">
    <h1>Create a tweet</h1>
    <p>
    <form>
        <textarea name="text" class="ribbitText"></textarea>
        <input type="submit" value="Ribbit!">
    </form>
    </p>
</div>
<div id="ribbits" class="panel left">
    <h1>Public tweets</h1>
    <div class="ribbitWrapper">
        <img class="avatar" src="gfx/user2.png">
        <span class="name">Kermit</span> @username <span class="time">15m</span>
        <p>
            Cras justo odio, dapibus ac facilisis in, egestas Vivamus sagittis lacus vel augue laoreet
            rutrum faucibus dolor auctor. <a href="#">http://net.tutsplus.com/tutorials/php/ ...</a>
        </p>
    </div>
    <div class="ribbitWrapper">
        <img class="avatar" src="gfx/user1.png">
        <span class="name">Frogger</span> @username <span class="time">15m</span>
        <p>
            Cras justo odio, dapibus ac facilisis in, egestas Vivamus sagittis lacus vel augue laoreet
            rutrum faucibus dolor auctor. <a href="#">http://net.tutsplus.com/tutorials/php/ ...</a>
        </p>
    </div>
    <div class="ribbitWrapper">
        <img class="avatar" src="gfx/user2.png">
        <span class="name">Kermit</span> @username <span class="time">15m</span>
        <p>
            Cras justo odio, dapibus ac facilisis in, egestas Vivamus sagittis lacus vel augue laoreet
            rutrum faucibus dolor auctor. <a href="#">http://net.tutsplus.com/tutorials/php/ ...</a>
        </p>
    </div>
    <div class="ribbitWrapper">
        <img class="avatar" src="gfx/user3.png">
        <span class="name">Hypnotoad</span> @username <span class="time">15m</span>
        <p>
            Cras justo odio, dapibus ac facilisis in, egestas Vivamus sagittis lacus vel augue laoreet
            rutrum faucibus dolor auctor. <a href="#">http://net.tutsplus.com/tutorials/php/ ...</a>
        </p>
    </div>
    <div class="ribbitWrapper">
        <img class="avatar" src="gfx/user2.png">
        <span class="name">Kermit</span> @username <span class="time">15m</span>
        <p>
            Cras justo odio, dapibus ac facilisis in, egestas Vivamus sagittis lacus vel augue laoreet
            rutrum faucibus dolor auctor. <a href="#">http://net.tutsplus.com/tutorials/php/ ...</a>
        </p>
    </div>
    <div class="ribbitWrapper">
        <img class="avatar" src="gfx/user3.png">
        <span class="name">Hypnotoad</span> @username <span class="time">15m</span>
        <p>
            Cras justo odio, dapibus ac facilisis in, egestas Vivamus sagittis lacus vel augue laoreet
            rutrum faucibus dolor auctor. <a href="#">http://net.tutsplus.com/tutorials/php/ ...</a>
        </p>
    </div>
</div>
{% endblock content %}

templates/pages/user_profile.html
{% extends '_base.html' %}
<!-- title tag -->
{% block title %} - Profile {% endblock title %}
<!-- end of title -->
{% load static %}
<!-- feeds content -->
{% block content %}
<div class="feeds-content dark-mode-2">
  <div class="feeds-header dark-mode-1 profile-bg">
    <div class="header-top border">
      <h4 class="light-text">Jane Smith</h4>
      <button type="button" class="follow-btn dark-mode-2">Follow</button>
    </div>
  </div>
  <div class="posts dark-mode-1">
    <div class="post border">
      <div class="user-avatar profile">
        <img src="{% static 'tweeter/images/user2.jpg' %}" />
      </div>
      <div class="post-content">
        <div class="post-user-info light-text">
          <h4>Jane Smith</h4>
          <p>@janesmith</p>
          <div class="action">
            <i class="action-item fas fa-ellipsis-h detail-icon"></i>
            <i class="action-item fas fa-edit detail-icon"></i>
          </div>
        </div>
        <p class="post-text light-text">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates
          et voluptatibus vel tenetur quos, id omnis sed error fuga
          necessitatibus.
        </p>
        <div class="detail">
          <div class="detail-item">
            <i class="fas fa-location-arrow detail-icon"></i>
            <p class="detail-text">Akure, Ondo State</p>
          </div>
          <div class="detail-item">
            <i class="fas fa-male detail-icon"></i>
            <p class="detail-text">Akure, Ondo State</p>
          </div>
          <div class="detail-item">
            <i class="far fa-calendar detail-icon"></i>
            <p class="detail-text">Akure, Ondo State</p>
          </div>
        </div>
        <div class="following light-text">
          <p class="following-paragraph"><span>711</span> Following</p>
          <p class="following-paragraph"><span>7.5K</span> Followers</p>
        </div>
      </div>
    </div>
    <div class="post border">
      <div class="user-avatar">
        <img src="{% static 'tweeter/images/user2.jpg' %}" />
      </div>
      <div class="post-content">
        <div class="post-user-info light-text">
          <h4>Helen Brown</h4>
          <i class="fas fa-check-circle"></i>
          <span>@helenbrown 15m</span>
        </div>
        <p class="post-text light-text">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates
          et voluptatibus vel tenetur quos, id omnis sed error fuga
          necessitatibus.
        </p>
        <div class="post-img">
          <img src="{% static 'tweeter/images/post-img-1.jpg' %}" />
        </div>
        <div class="post-icons">
          <i class="far fa-comment"></i>
          <i class="fas fa-retweet"></i>
          <i class="far fa-heart"></i>
          <i class="fas fa-share-alt"></i>
        </div>
      </div>
    </div>
  </div>
  <!-- follow side bar -->
  {% include 'includes/_followsidebar.html' %}
  <!-- end of follow side bar -->
</div>
<!-- end of feeds content -->

<!-- post modal -->
{% include 'includes/_modal.html' %}
<!-- end of post modal -->

<!-- sidebar -->
{% include 'includes/_sidebar.html' %}
<!-- end of sidebar -->
{% endblock content %}